-- 
-- Created by SQL::Translator::Producer::PostgreSQL
-- Created on Fri Feb 19 18:00:41 2010
-- 
--
-- Table: transfac__antibody__dm
--
CREATE TABLE "transfac__antibody__dm" (
  "tf_antibody_id" bigserial NOT NULL,
  "tf_id_key" integer NOT NULL,
  "antibody_id" integer DEFAULT NULL,
  "official_name" character varying(64) DEFAULT NULL,
  "short_name" character varying(64) DEFAULT NULL,
  "target_species" character varying(64) DEFAULT NULL,
  "target_id" character varying(64) DEFAULT NULL,
  "target_public_name" character varying(64) DEFAULT NULL,
  "host_species" character varying(64) DEFAULT NULL,
  "purified" smallint DEFAULT NULL,
  "monoclonal" smallint DEFAULT NULL,
  "contribute_lab" character varying(32) DEFAULT NULL,
  "wiki_perma_url" character varying(64) DEFAULT NULL,
  PRIMARY KEY ("tf_antibody_id")
);
CREATE INDEX "tf_id_key" on "transfac__antibody__dm" ("tf_id_key");

--
-- Table: transfac__binding_sites__main
--
CREATE TABLE "transfac__binding_sites__main" (
  "tf_id_key" integer NOT NULL,
  "bs_id_key" bigserial NOT NULL,
  "bs_id" integer NOT NULL,
  "bs_chromosome_name" character varying(10) NOT NULL,
  "bs_chromosome_start" bigint NOT NULL,
  "bs_chromosome_end" bigint NOT NULL,
  "bs_chromosome_strand" character(1) NOT NULL,
  "q_value" numeric NOT NULL,
  "bs_sequence" bytea,
  PRIMARY KEY ("bs_id_key")
);
CREATE INDEX "tf_id_key" on "transfac__binding_sites__main" ("tf_id_key");

--
-- Table: transfac__binding_sites_genes__dm
--
CREATE TABLE "transfac__binding_sites_genes__dm" (
  "bs_gene_id" bigserial NOT NULL,
  "bs_id_key" bigint NOT NULL,
  "gene_id" character varying(20) NOT NULL,
  "relative_position" smallint DEFAULT NULL,
  "distance" bigint NOT NULL,
  PRIMARY KEY ("bs_gene_id")
);
CREATE INDEX "bs_id_key" on "transfac__binding_sites_genes__dm" ("bs_id_key");

--
-- Table: transfac__cellline__dm
--
CREATE TABLE "transfac__cellline__dm" (
  "tf_cellline_id" bigserial NOT NULL,
  "tf_id_key" integer NOT NULL,
  "official_name" character varying(64) DEFAULT NULL,
  "short_name" character varying(64) DEFAULT NULL,
  "species" character varying(64) DEFAULT NULL,
  "genotype" character varying(200) DEFAULT NULL,
  "sex" character varying(20) DEFAULT NULL,
  "tissue_ontology_name" bytea,
  "cell_type" character varying(50) DEFAULT NULL,
  "developmental_stage_ontology_name" bytea,
  "contribute_lab" character varying(32) DEFAULT NULL,
  "wiki_perma_url" character varying(64) DEFAULT NULL,
  PRIMARY KEY ("tf_cellline_id")
);
CREATE INDEX "tf_id_key" on "transfac__cellline__dm" ("tf_id_key");

--
-- Table: transfac__developmental_stage__dm
--
CREATE TABLE "transfac__developmental_stage__dm" (
  "tf_devstage_id" bigserial NOT NULL,
  "tf_id_key" integer NOT NULL,
  "official_name" character varying(64) DEFAULT NULL,
  "short_name" character varying(64) DEFAULT NULL,
  "species" character varying(64) DEFAULT NULL,
  "sex" character varying(20) DEFAULT NULL,
  "ontology_name" bytea,
  "wiki_perma_url" character varying(64) DEFAULT NULL,
  PRIMARY KEY ("tf_devstage_id")
);
CREATE INDEX "tf_id_key" on "transfac__developmental_stage__dm" ("tf_id_key");

--
-- Table: transfac__experiment_dm
--
CREATE TABLE "transfac__experiment_dm" (
  "tf_experiment_id" bigserial NOT NULL,
  "dcc_id" integer NOT NULL,
  "tf_id_key" integer NOT NULL,
  "title" character varying(255) DEFAULT NULL,
  PRIMARY KEY ("tf_experiment_id")
);
CREATE INDEX "tf_id_key" on "transfac__experiment_dm" ("tf_id_key");

--
-- Table: transfac__strain__dm
--
CREATE TABLE "transfac__strain__dm" (
  "tf_strain_id" bigserial NOT NULL,
  "tf_id_key" integer NOT NULL,
  "strain_id" integer DEFAULT NULL,
  "official_name" character varying(64) DEFAULT NULL,
  "short_name" character varying(64) DEFAULT NULL,
  "species" character varying(64) DEFAULT NULL,
  "genotype" character varying(200) DEFAULT NULL,
  "trangenic_type" character varying(200) DEFAULT NULL,
  "tag" character varying(64) DEFAULT NULL,
  "contribute_lab" character varying(32) DEFAULT NULL,
  "wiki_perma_url" character varying(64) DEFAULT NULL,
  PRIMARY KEY ("tf_strain_id")
);
CREATE INDEX "tf_id_key" on "transfac__strain__dm" ("tf_id_key");

--
-- Table: transfac__tissue__dm
--
CREATE TABLE "transfac__tissue__dm" (
  "tf_tissue_id" bigserial NOT NULL,
  "tf_id_key" integer NOT NULL,
  "official_name" character varying(64) DEFAULT NULL,
  "short_name" character varying(64) DEFAULT NULL,
  "species" character varying(64) DEFAULT NULL,
  "sex" character varying(20) DEFAULT NULL,
  "ontology_name" bytea,
  "contribute_lab" character varying(32) DEFAULT NULL,
  "wiki_perma_url" character varying(64) DEFAULT NULL,
  PRIMARY KEY ("tf_tissue_id")
);
CREATE INDEX "tf_id_key" on "transfac__tissue__dm" ("tf_id_key");

--
-- Table: transfac__transcriptional_factor__main
--
CREATE TABLE "transfac__transcriptional_factor__main" (
  "tf_id_key" serial NOT NULL,
  "dcc_id" integer NOT NULL,
  "species" character varying(64) NOT NULL,
  "gene_id" character varying(20) DEFAULT NULL,
  "public_name" character varying(20) NOT NULL,
  "tf_chromosome_name" character varying(10) DEFAULT NULL,
  "tf_chromosome_start" bigint DEFAULT NULL,
  "tf_chromosome_end" bigint DEFAULT NULL,
  "tf_chromosome_strand" character(1) DEFAULT NULL,
  "concise_description" text,
  PRIMARY KEY ("tf_id_key"),
  CONSTRAINT "dcc_id" UNIQUE ("dcc_id")
);
CREATE INDEX "public_name" on "transfac__transcriptional_factor__main" ("public_name");

